run:
	java sim.Simulator --players random random random random random random random random random random -r 100 -s 10 -l log.txt

gui:
	java sim.Simulator --players random random random random random random random random random random -r 100 -s 10 --gui -l log.txt

compile:
	javac */*.java

clean:
	rm */*.class
