run:
	java -cp .:org.json.jar sim.Simulator --players random random random random random random random random random random -r 10 -s 10 -l log.txt -e games.csv

gui:
	java -cp .:org.json.jar sim.Simulator --players random random random random random random random random random random -r 10 -s 10 -f 10 --gui -l log.txt -e games.csv -c

compile:
	javac -cp .:org.json.jar */*.java

clean:
	rm */*.class
