run:
	java -cp .:org.json.jar sim.Simulator --players random random random random random random random random random random -r 10 -s 10 -l log.txt

gui:
	java -cp .:org.json.jar sim.Simulator --players random random random random random random random random random random -r 10 -s 10 --gui -l log.txt

compile:
	javac -cp .:org.json.jar */*.java

clean:
	rm */*.class
